version: '3'
services:
  guidelines:
    build:
      context: .
      dockerfile: Dockerfile.guidelines
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - ENDPOINT_URL=http://stardog:5820/guidelines/query
      - UPDATE_URL=http://stardog:5820/guidelines/update
  stardog:
    build:
      context: .
      dockerfile: Dockerfile.stardog
    environment:
      - STARDOG_START_PARAMS=--disable-security
    volumes:
      - ./src/data/:/var/data
    ports:
      - "127.0.0.1:5820:5820"
