FROM python:2.7.13-wheezy

MAINTAINER rinke.hoekstra@vu.nl

ENV GUIDELINES_APP="/usr/local/guidelines"

COPY ./requirements.txt /requirements.txt
RUN pip install -r requirements.txt

COPY ./src ${GUIDELINES_APP}

COPY entrypoint.sh /sbin/entrypoint.sh
RUN chmod 755 /sbin/entrypoint.sh

WORKDIR ${GUIDELINES_APP}
ENTRYPOINT ["/sbin/entrypoint.sh"]
CMD ["app:start"]
EXPOSE 5000
